<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class NieruchomosciSeeder extends Seeder
{

    public function run()
    {
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Luksusowy dom',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 350000,
            'powierzchnia' => 200,
            'sypialnie' => 3,
            'garaże' => 1,
            'łazienki' => 2,
            'Miasto' => 'Rzeszów',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-1.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-2.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-3.jpg',
            'id_agenta' => 1,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Dom rodzinny',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 400000,
            'powierzchnia' => 300,
            'sypialnie' => 5,
            'garaże' => 2,
            'łazienki' => 2,
            'Miasto' => 'Kraków',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-2.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-4.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-5.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-6.jpg',
            'id_agenta' => 2,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Przytulna kawalerka',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 150000,
            'powierzchnia' => 134,
            'sypialnie' => 1,
            'garaże' => 0,
            'łazienki' => 1,
            'Miasto' => 'Zalesie',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/kawalerka.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homeskawalerka-inside.jpg',
            'id_agenta' => 3,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Apartament w Mariocie',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 800000,
            'powierzchnia' => 300,
            'sypialnie' => 3,
            'garaże' => 1,
            'łazienki' => 3,
            'Miasto' => 'Warszawa',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/mariot.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/mariot-inside1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/mariot-inside2.jpg',
            'id_agenta' => 3,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Fajny domek',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 650000,
            'powierzchnia' => 250,
            'sypialnie' => 4,
            'garaże' => 2,
            'łazienki' => 3,
            'Miasto' => 'Amsterdam',
            'Kraj' => 'Holandia',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-3.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-2.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-3.jpg',
            'id_agenta' => 2,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Fajny domek2',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 600000,
            'powierzchnia' => 450,
            'sypialnie' => 2,
            'garaże' => 2,
            'łazienki' => 5,
            'Miasto' => 'Wrocław',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-4.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-2.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-3.jpg',
            'id_agenta' => 2,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Fajny domek3',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 500000,
            'powierzchnia' =>267,
            'sypialnie' => 4,
            'garaże' => 1,
            'łazienki' => 2,
            'Miasto' => 'Jasło',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-5.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-2.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-3.jpg',
            'id_agenta' => 3,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
        DB::table('nieruchomosci')->insert([
            'tytuł'=>'Fajny domek4',
            'opis'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic',
            'cena' => 900000,
            'powierzchnia' =>330,
            'sypialnie' => 5,
            'garaże' => 3,
            'łazienki' => 3,
            'Miasto' => 'Krosno',
            'Kraj' => 'Polska',
            'zdjecie_opcjonalne0' => '/assets/img/homes/home-6.jpg',
            'zdjecie_opcjonalne1' => '/assets/img/homes/home-inside-1.jpg',
            'zdjecie_opcjonalne2' => '/assets/img/homes/home-inside-2.jpg',
            'zdjecie_opcjonalne3' => '/assets/img/homes/home-inside-3.jpg',
            'id_agenta' => 1,
            'Czy_opublikowany' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s"),
        ]);
    }
}
